### ISSUE TITLE
testing: no such file or directory for database

### ISSUE THREAD

**Issue by voidzero** [goatpig/BitcoinArmory#101]
Hi,

I was just going to test the testing branch, and I'm getting 'no such file or directory' when armory tries to open the database. I'm not sure which database - Armory's or Bitcoin's, and my config is a little bit exotic so I'll explain how I've set it up.

Bitcoin: runs with `--datadir=~/.bitcoin/data`
Armory: runs with `--datadir=~/.armory --satoshi-datadir=~/.bitcoin/data`

The error:

```
ArmoryUtils.py:642 - Executing popen: ['/usr/bin/ArmoryDB', '--db-type="DB_FULL"', '--spawnId="7xxUwTveyby64u98RMbv7UpCATStQ4vQyv6W5pmpaxH4"', '--satoshi-datadir="/home/voidzero/.bitcoin/data/blocks"', '--dbdir="/home/voidzero/.armory/databases"']
2016-09-30 11:55 (ERROR) -- ArmoryQt.py:2211 - Failed to start Armory database: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/armory/ArmoryQt.py", line 2198, in startArmoryDBIfNecessary
    spawnId = TheSDM.spawnDB(TheBDM.armoryDBDir)
  File "/usr/lib64/python2.7/site-packages/armory/SDM.py", line 526, in spawnDB
    launchProcess(pargs, **kargs)
  File "/usr/lib64/python2.7/site-packages/armory/armoryengine/ArmoryUtils.py", line 645, in launchProcess
    return Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE, *args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by goatpig** [comment]
Start ArmoryDB manually with the same command line (minus the spawnID), see what it has to say for itself. You can also get some verbose in dbLog.txt if the DB binary got this far

**Comment by voidzero** [comment]
oh derp, I didn't even notice the name of the ArmoryDB binary. That's what was missing, sorry hehe, I've installed it now. I suppose I need to run a --rebuild on the first run?

**Comment by goatpig** [comment]
If you want to use the same db folder, yes. Otherwise point it somewhere else with the --dbir cli arg.

**Comment by voidzero** [comment]
Alright, got it. Thanks a lot.
