### ISSUE TITLE
dev: errors right after starting up the client

### ISSUE THREAD

**Issue by voidzero** [goatpig/BitcoinArmory#145]
Hope it's ok for me to file issues against the dev tree. If not then of course feel free to let me know.

The following occurs right after starting Armory:

```
BDM is ready!
(ERROR) Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/armory/ArmoryQt.py", line 5837, in handleCppNotification
    self.updateWalletData()
  File "/usr/lib64/python2.7/site-packages/armory/ArmoryQt.py", line 5824, in updateWalletData
    self.walletMap[wltid].getAddrDataFromDB()
  File "/usr/lib64/python2.7/site-packages/armory/armoryengine/PyBtcWallet.py", line 52, in inner
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/armory/armoryengine/PyBtcWallet.py", line 3119, in getAddrDataFromDB
    countList = self.cppWallet.getAddrTxnCountsFromDB()
  File "/usr/lib64/python2.7/site-packages/armory/CppBlockUtils.py", line 1375, in getAddrTxnCountsFromDB
    def getAddrTxnCountsFromDB(self): return _CppBlockUtils.BtcWallet_getAddrTxnCountsFromDB(self)
RuntimeError: ser/deser type error: 
expected type id: 4
got type id: 2 instead


Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/armory/ArmoryQt.py", line 5837, in handleCppNotification
    self.updateWalletData()
  File "/usr/lib64/python2.7/site-packages/armory/ArmoryQt.py", line 5824, in updateWalletData
    self.walletMap[wltid].getAddrDataFromDB()
  File "/usr/lib64/python2.7/site-packages/armory/armoryengine/PyBtcWallet.py", line 52, in inner
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/armory/armoryengine/PyBtcWallet.py", line 3119, in getAddrDataFromDB
    countList = self.cppWallet.getAddrTxnCountsFromDB()
  File "/usr/lib64/python2.7/site-packages/armory/CppBlockUtils.py", line 1375, in getAddrTxnCountsFromDB
    def getAddrTxnCountsFromDB(self): return _CppBlockUtils.BtcWallet_getAddrTxnCountsFromDB(self)
RuntimeError: ser/deser type error: 
expected type id: 4
got type id: 2 instead
```

**Comment by goatpig** [comment]
No it's not. dev is instable by definition. Testing code goes into testing, releases in master.
