### ISSUE TITLE
Using --thread-count option prevents ArmoryDB from launching

### ISSUE THREAD

**Issue by jpdied** [goatpig/BitcoinArmory#160]
If you add --thread-count to your command line for ArmoryQT, ArmoryDB will fail to be launched with the error:
2016-12-28 16:11 (INFO) -- ArmoryQt.py:2257 - setSatoshiPaths
2016-12-28 16:11 (ERROR) -- ArmoryQt.py:2211 - Failed to start Armory database: cannot concatenate 'str' and 'int' objects
Traceback (most recent call last):
  File "ArmoryQt.py", line 2198, in startArmoryDBIfNecessary
  File "SDM.pyc", line 519, in spawnDB
TypeError: cannot concatenate 'str' and 'int' objects

Full log attached.
[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/676293/armorylog.txt)

**Comment by goatpig** [comment]
Python code is failing to construct the CLI arg string properly when spawning the DB. I'll fix it for the next version. 

For now, you'll have to manage the DB manually if you want to use this setting.
