### ISSUE TITLE
Armory 0.95.1 Crashes On Launch | KeyError: 'rpcuser'

### ISSUE THREAD

**Issue by airbeef** [goatpig/BitcoinArmory#167]
Issue: Armory crashes upon launch with notice to check ArmoryQt.exe.

Steps:
- Attempt to send bitcoin to Bitsquare wallet twice

Results:
- Armory wallet refuses to send coin to Bitsquare wallet [Note: Armory wallet hangs during send then freezes]. Upon rebooting, the following error is thrown:

(ERROR) ArmoryUtils.pyc:3230 - Error in pybkgdthread: 'rpcuser'
Traceback (most recent call last):
  File "armoryengine\ArmoryUtils.pyc", line 3228, in run
  File "armoryengine\ArmoryUtils.pyc", line 3165, in funcPartial
  File "SDM.pyc", line 482, in pollBitcoindState
  File "SDM.pyc", line 696, in getSDMStateLogic
  File "SDM.pyc", line 834, in getTopBlockInfo
  File "SDM.pyc", line 826, in updateTopBlockInfo
  File "SDM.pyc", line 754, in createProxy
KeyError: 'rpcuser'
(ERROR) Traceback (most recent call last):
  File "ArmoryQt.py", line 6909, in <module>
  File "ArmoryQt.py", line 703, in __init__
  File "ArmoryQt.py", line 5324, in setDashboardDetails
  File "SDM.pyc", line 663, in getSDMState
  File "SDM.pyc", line 696, in getSDMStateLogic
  File "SDM.pyc", line 834, in getTopBlockInfo
  File "SDM.pyc", line 826, in updateTopBlockInfo
  File "SDM.pyc", line 754, in createProxy
KeyError: 'rpcuser'

Traceback (most recent call last):
  File "ArmoryQt.py", line 6909, in <module>
  File "ArmoryQt.py", line 703, in __init__
  File "ArmoryQt.py", line 5324, in setDashboardDetails
  File "SDM.pyc", line 663, in getSDMState
  File "SDM.pyc", line 696, in getSDMStateLogic
  File "SDM.pyc", line 834, in getTopBlockInfo
  File "SDM.pyc", line 826, in updateTopBlockInfo
  File "SDM.pyc", line 754, in createProxy
KeyError: 'rpcuser'

Mitigation Steps:
- Uninstalled and reinstall Armory, deleting all files in Roaming. Paper backup (ver. 1.35)and digital wallet backup made (both 2014 & 2017) [error continues]
- Updated Bitcoin Core to 0.13.2 and allowed blockchain to update. [Error continues]

**Comment by goatpig** [comment]
Delete rpcuser and rpcpass from bitcoin.conf

**Comment by airbeef** [comment]
Got it. Didn't have a generated bitcoion,conf, so I generated one via copy/paste [the generic example](https://github.com/bitcoin/bitcoin/blob/master/contrib/debian/examples/bitcoin.conf), turned the .txt file into a .conf file and placed it in my **C:\Users\<username>\AppData\Roaming\Bitcoin folder** since it didn't generate one.  I'm up and running now. Thank you.

**Comment by goatpig** [comment]
It most likely failed to generate one for you because Armory does not have write permission to that Bitcoin datadir.

If you want to use auto bitcoind and/or get fee/byte estimates from your node, you need to set server=1 in the .conf
