### ISSUE TITLE
RBF Bump Fee

### ISSUE THREAD

**Issue by Arccotangent** [goatpig/BitcoinArmory#218]
Not sure if this is a known issue, but I tried to bump the fee on an RBF flagged transaction, but when I clicked Bump Fee, this error message was printed to the terminal:
```
-ERROR - 1494452387: (TransactionBatch.cpp:62) TxBatch processing error at line 4
-ERROR - 1494452387: (TransactionBatch.cpp:63) TxBatch error message: Invalid entry termination
(ERROR) Traceback (most recent call last):
  File "/usr/local/bin/../lib/armory/ArmoryQt.py", line 3340, in showContextMenuLedger
    self.bumpFee(wltID, txHash)
  File "/usr/local/bin/../lib/armory/ArmoryQt.py", line 5891, in bumpFee
    dlgSpend.frame.prefillFromBatch(batchStr)
  File "/usr/local/lib/armory/ui/TxFrames.py", line 1295, in prefillFromBatch
    self.prefill(prefillData)
  File "/usr/local/lib/armory/ui/TxFrames.py", line 1342, in prefill
    changeAddr = prefill['change']
KeyError: 'change'

Traceback (most recent call last):
  File "/usr/local/bin/../lib/armory/ArmoryQt.py", line 3340, in showContextMenuLedger
    self.bumpFee(wltID, txHash)
  File "/usr/local/bin/../lib/armory/ArmoryQt.py", line 5891, in bumpFee
    dlgSpend.frame.prefillFromBatch(batchStr)
  File "/usr/local/lib/armory/ui/TxFrames.py", line 1295, in prefillFromBatch
    self.prefill(prefillData)
  File "/usr/local/lib/armory/ui/TxFrames.py", line 1342, in prefill
    changeAddr = prefill['change']
KeyError: 'change'
```

I am on Arch Linux, running Armory 0.96

**Comment by goatpig** [comment]
Thanks for the report, will look into it

**Comment by goatpig** [comment]
Does your tx have no change?

**Comment by Arccotangent** [comment]
The transaction didn't appear to change at all. If there was supposed to be a dialog box when that is clicked, none popped up.

**Comment by goatpig** [comment]
I'm asking whether the tx you are trying to bump has no change

**Comment by goatpig** [comment]
Fixed in this commit:

https://github.com/goatpig/BitcoinArmory/commit/94c915232fb8365543c7984a450a855e39aec0b2
