### ISSUE TITLE
Examining Coinbase transactions fails

### ISSUE THREAD

**Issue by achow101** [goatpig/BitcoinArmory#23]
It is not possible to view the details of a coinbase transaction. This is the error:
```
Traceback (most recent call last):
  File "/home/andy/bitcoin/armory/BitcoinArmory/ArmoryQt.py", line 3940, in dblClickLedger
    self.showLedgerTx()
  File "/home/andy/bitcoin/armory/BitcoinArmory/ArmoryQt.py", line 3962, in showLedgerTx
    DlgDispTxInfo( pytx, self.walletMap[wltID], self, self, txtime=txtime).exec_()
  File "/home/andy/bitcoin/armory/BitcoinArmory/qtdialogs.py", line 5667, in __init__
    self.data = extractTxInfo(pytx, txtime)
  File "/home/andy/bitcoin/armory/BitcoinArmory/qtdialogs.py", line 5614, in extractTxInfo
    scraddr = addrStr_to_scrAddr(TxInExtractAddrStrIfAvail(txin))
  File "/home/andy/bitcoin/armory/BitcoinArmory/armoryengine/ArmoryUtils.py", line 1622, in addrStr_to_scrAddr
    atype, a160 = addrStr_to_hash160(addrStr)
  File "/home/andy/bitcoin/armory/BitcoinArmory/armoryengine/ArmoryUtils.py", line 2167, in addrStr_to_hash160
    raise BadAddressError('Address string is %d bytes' % len(binStr))
armoryengine.ArmoryUtils.BadAddressError: Address string is 0 bytes
```
This is most obviously seen when using the regtest mode created in #22

**Comment by goatpig** [comment]
Will fix in 0.95
