### ISSUE TITLE
Can't backup wallet, no UI feedback

### ISSUE THREAD

**Issue by TimSylvester** [goatpig/BitcoinArmory#234]
Trying to use Wallet properties -> Backup This Wallet -> Export Key Lists, it accepts wallet passphrase and decrypts, then silently returns to the Backup Center window.

Same results in versions 0.96-beta-a3d01aa722 and 0.96.0.1-beta-654b380411.

Log shows the following:

```
2017-05-22 12:23:34 (ERROR) -- Traceback (most recent call last):
  File "ui\WalletFrames.pyc", line 1136, in clickedDoIt
  File "qtdialogs.pyc", line 4943, in __init__
  File "qtdialogs.pyc", line 5002, in rewriteList
  File "CppBlockUtils.pyc", line 4032, in getAddrObjByIndex
RuntimeError: invalid asset index
```

Digital backup is similar, either encrypted or not:

```
2017-05-22 14:57 (ERROR) -- Traceback (most recent call last):
  File "ui\WalletFrames.pyc", line 1119, in clickedDoIt
  File "ArmoryQt.py", line 1614, in makeWalletCopy
  File "armoryengine\Decorators.pyc", line 48, in inner
  File "ArmoryQt.py", line 2224, in getFileSave
TypeError: sequence item 0: expected string, QString found

2017-05-22 14:57 (ERROR) -- Traceback (most recent call last):
  File "ui\WalletFrames.pyc", line 1117, in clickedDoIt
  File "ArmoryQt.py", line 1614, in makeWalletCopy
  File "armoryengine\Decorators.pyc", line 48, in inner
  File "ArmoryQt.py", line 2224, in getFileSave
TypeError: sequence item 0: expected string, QString found
```

Wallet consistency check looks good:

```
Checking wallet 'Local' (ID: Mn6FjuJ7) on Mon May 22 11:42:51 2017 
Wallet contains private keys and uses encryption
Highest used index: 101
The wallet file is 57686 bytes, of which 57686 bytes were read
202 chain addresses, 1 imported keys and 73 comments were found
Found 202 chained address entries
No byte errors were found in the wallet file
All chained addresses were arranged sequentially in the wallet file
There are no gaps in the address chain
No chained address fork was found
No chaincode corruption was found
All chained public keys are valid EC points
No chained public key is missing
All entries were saved under their matching hashVal
All chained public keys match their respective private keys
Found 1 imported address entries
No errors were found within the imported address entries
0 errors were found
Recovery done
```

**Comment by goatpig** [comment]
Fixed on the testing branch, either build it yourself or wait for the next testing build
