### ISSUE TITLE
0.96.1 on macos stuck at start (.startBitcoindIfNecessary)

### ISSUE THREAD

**Issue by joernroeder** [goatpig/BitcoinArmory#277]
Hey,
i've upgraded to armory `0.96.1` from version `0.95.1` and now it stucks at the loading sequence. I'm tailing the logs during start `tail -f ~/Library/Application\ Support/Armory/armorylog.txt` and the last logs are:
```
2017-07-31 19:32:32 (INFO) -- ArmoryQt.py:1825 - startBitcoindIfNecessary
2017-07-31 19:32:32 (INFO) -- ArmoryQt.py:1913 - Setting netmode: 1
```

I'm also seeing the following error popping up almost once a second in the  `armorycpplog.txt`:
```
ERROR - 20:07:58: (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unexpected fcgi header version
```

i'm using the `bitcoind` (v0.14.2) binary or the qt wallet, both locally and without a proxy (tor) e.g.

**Comment by goatpig** [comment]
Need to see full logs, from client and db.

**Comment by joernroeder** [comment]
@goatpig i removed my log files, restarted `bitcoind` and armory. The following log files are capturing a single start:

__armoryccplog.txt__

```
Log file opened at 00:48:40: ~/Library/Application Support/Armory/armorycpplog.txt
-ERROR - 00:48:40: (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unexpected fcgi header version

...
...
(99 times a second)
```

__armorylog.txt__

```
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1138 - C++ block utilities loaded successfully
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:667 - Executing popen: sysctl hw.memsize
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:667 - Executing popen: sysctl -n machdep.cpu.brand_string
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1255 - 
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1256 - 
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1257 - 
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1258 - ************************************************************
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1259 - Invoked: /Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1260 - ************************************************************
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1261 - Loading Armory Engine:
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1262 -    Armory Version        : 0.96.1
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1263 -    Armory Build:         : b77932c8e3
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1264 -    PyBtcWallet  Version  : 1.35
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1265 - Detected Operating system: MacOSX
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1266 -    OS Variant            : 10.12.5
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1267 -    User home-directory   : ~/Library/Application Support
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1268 -    Satoshi BTC directory : ~/Library/Application Support/Bitcoin/
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1269 -    Armory home dir       : ~/Library/Application Support/Armory/
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1270 - Detected System Specs    : 
...
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1279 - 
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1280 - Network Name: Main Network
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1281 - Satoshi Port: 8333
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1282 - Do wlt check: True
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1283 - Named options/arguments to armoryengine.py:
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     thread_count    : -1
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     rescan          : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     ignoreAllZC     : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     rescanBalance   : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     disableModules  : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     port            : None
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     interport       : 8223
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     coverageOutputDir: None
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     forceWalletCheck: False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     regtest         : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     rebuild         : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     nettimeout      : 2
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     datadir         : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     clearMempool    : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     offline         : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     armoryDBDir     : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     armorydb_port   : 9001
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     psn             : None
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     satoshiPort     : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     useTorSettings  : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     netlog          : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     keypool         : 100
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     coverageInclude : None
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     forceOnline     : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     redownload      : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     rpcBindAddr     : 127.0.0.1
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     armorydb_ip     : 127.0.0.1
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     multisigFile    : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     ram_usage       : -1
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     mtdebug         : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     logDisable      : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     settingsPath    : ~/Library/Application Support/Armory/ArmorySettings.txt
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     language        : en
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     db_type         : DB_FULL
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     doDebug         : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     enableDetSign   : True
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     disableConfPermis: False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     testnet         : False
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     rpcport         : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     satoshiHome     : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     satoshiRpcport  : DEFAULT
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     logFile         : ~/Library/Application Support/Armory/ArmoryQt.py.log.txt
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1285 -     verbosity       : None
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1286 - Other arguments:
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1289 - ************************************************************
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:1692 - C++ block utilities loaded successfully
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:3590 - Using settings file: ~/Library/Application Support/Armory/ArmorySettings.txt
2017-08-01 00:48:40 (ERROR) -- ArmoryUtils.py:3747 - Unsupported language  specified. Defaulting to English (en)
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:3750 - Using Language: en
2017-08-01 00:48:40 (INFO) -- BDM.py:365 - Using the asynchronous/multi-threaded BlockDataManager.
2017-08-01 00:48:40 (INFO) -- BDM.py:366 - Blockchain operations will happen in the background.  
2017-08-01 00:48:40 (INFO) -- BDM.py:367 - Devs: check TheBDM.getState() before asking for data.
2017-08-01 00:48:40 (INFO) -- BDM.py:368 - Registering addresses during rescans will queue them for 
2017-08-01 00:48:40 (INFO) -- BDM.py:369 - inclusion after the current scan is completed.
2017-08-01 00:48:40 (INFO) -- ArmoryUtils.py:3590 - Using settings file: ~/Library/Application Support/Armory/ArmorySettings.txt
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:2050 - loadWalletsAndSettings
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:2110 - Loading wallets...
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:2175 - Number of wallets read in: 1
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:2180 -    Wallet (ID):   "Primary Wallet                  "   (Encrypted)
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:2185 - Loading Multisig Lockboxes
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1752 - acquiring process mutex...
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1391 - setupUriRegistration
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:565 - Usermode: Expert
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1687 - Changing usermode:
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1688 -    From: Expert
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1696 -      To: Expert
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1825 - startBitcoindIfNecessary
2017-08-01 00:48:40 (INFO) -- ArmoryQt.py:1913 - Setting netmode: 1
```

__dbLog.txt__

After i prefixed all logfiles to generate new one for the test launch no dbLog.txt was created. It seems like it didn't get to that part of the startup sequence.

**Comment by goatpig** [comment]
Start the DB manually, see where that gets you.

**Comment by joernroeder** [comment]
hm, something is already listening on port `9001`but `netstat -al | grep 9001` doesn't show me anything.

```
-INFO  - 01:19:22: (main.cpp:32) Running on 8 threads
-INFO  - 01:19:22: (main.cpp:33) Ram usage level: 4
-INFO  - 01:19:22: (BlockUtils.cpp:908) blkfile dir: /Users/joernroeder/Library/Application Support/Bitcoin/blocks
-INFO  - 01:19:22: (BlockUtils.cpp:909) lmdb dir: /Users/joernroeder/Library/Application Support/Armory/databases
-INFO  - 01:19:22: (lmdb_wrapper.cpp:388) Opening databases...
-INFO  - 01:19:22: (./BDM_Server.h:249) Listening on port 9001
-ERROR - 01:19:22: (BDM_Server.cpp:1230) There is already a process listening on 127.0.0.1:9001
-ERROR - 01:19:22: (BDM_Server.cpp:1232) ArmoryDB cannot start under these conditions. Shutting down!
-ERROR - 01:19:22: (BDM_Server.cpp:1233) Make sure to shutdown the conflicting processbefore trying again (most likely another ArmoryDB instance).
```

**Comment by goatpig** [comment]
Set the DB's listening port with --fcgi-port
Set the client's to use that port with --armorydb-port

**Comment by joernroeder** [comment]
@goatpig #TurnItOffAndOnAgain helped in my case. I don't know what was hanging around at 9001 but armory is now running as expected. thanks for helping me out so fast at this historical bitcoin day, Stay save! 🛳

**Comment by goatpig** [comment]
I'm not sure what's going on here. Consider that since 0.96.1, the DB port is randomized when spawned from the client, therefor it can't be the port issue per se. 

The port error message can be mislabeled, where it fails to create the listen socket (firewall/security features? not familiar with OSX idiosyncrasies), and reports this as the port being in use instead (one size fits all error verbose).

**Comment by joernroeder** [comment]
ah, shit – too early. spotlight picked my backuped 0.95.1 version. i'll try the parameters now...

**Comment by joernroeder** [comment]
i'm still seeing 9001 ath the listener port...

```
/Applications/Armory.app/Contents/MacOS/py/usr/local/bin/ArmoryDB --fcgi-port 55555
logging in
-INFO  - 01:41:04: (main.cpp:32) Running on 8 threads
-INFO  - 01:41:04: (main.cpp:33) Ram usage level: 4
-INFO  - 01:41:04: (./BDM_Server.h:249) Listening on port 9001
-ERROR - 01:41:04: (BDM_Server.cpp:1230) There is already a process listening on 127.0.0.1:9001
-ERROR - 01:41:04: (BDM_Server.cpp:1232) ArmoryDB cannot start under these conditions. Shutting down!
-ERROR - 01:41:04: (BDM_Server.cpp:1233) Make sure to shutdown the conflicting processbefore trying again (most likely another ArmoryDB instance).

```

**Comment by goatpig** [comment]
Armory cli args use =

--fcgi-port=55555

**Comment by goatpig** [comment]
You can also pass the port in a armorydb.conf

**Comment by joernroeder** [comment]
thanks! it's finally running now and i'm seeing connection logs in `bitcoind`
```
2017-07-31 23:52:27 receive version message: Armory:0.96.1: version 70012, blocks=-1, us=127.0.0.1:8333, peer=13
```

after the initial test i've added `armorydb_port` to the config file but it seems like the database isn't running at all – neither on 9001 nor 55555. I was able to start it manually and after a restart of armory it started to reparse `parsed block file #26` the block files.

**Comment by goatpig** [comment]
I see no clue as to why the client is failing to spawn the DB in your logs. If you have some Python in you, you can put print statements in the in the following methods to see where it chokes:

https://github.com/goatpig/BitcoinArmory/blob/master/ArmoryQt.py#L1777
https://github.com/goatpig/BitcoinArmory/blob/master/SDM.py#L355

**Comment by joernroeder** [comment]
it's returning here with `localDBPort == 9001`: https://github.com/goatpig/BitcoinArmory/blob/master/ArmoryQt.py#L1788

**Comment by goatpig** [comment]
When I think about it, wasn't there something about spawning processes with cli args failing on OSX? If the DB can't get the --cookie cli arg, it won't randomize port. 

Your best bet is to enforce your ports through the config files. Any arg the client and db can take you can put in the relevant .conf:

armoryqt.conf
armorydb.conf

**Comment by joernroeder** [comment]
i'm spawning processes with nodejs regularly and never had a problem with it. I've also added 55555 as my db port to ArmorySettings.txt and thought #276 could be related as used the default 9001 port.
so i'm not using the ArmorySettings.txt within the Appliation Support/Armory directory and placing the cli args into the coressponding .conf files instead?

**Comment by goatpig** [comment]
The .txt settings is only for settings you can modify from the GUI, which connectivity is not a part of. 

The .confs inject the arguments they have to argv on startup, so they simply mimic manually entered cli args. These won't overwrite manual arguments however.

**Comment by joernroeder** [comment]
ok, thanks for the explaination. i've created the files but it's still the default port which is logged out before the return statement i found earlier.

```
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1260 - ************************************************************
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1261 - Invoked: /Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py --armorydb-port=55555
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1262 - ************************************************************
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1263 - Loading Armory Engine:
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1264 -    Armory Version        : 0.96.1
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1265 -    Armory Build:         : b77932c8e3
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1266 -    PyBtcWallet  Version  : 1.35
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1267 - Detected Operating system: MacOSX
...
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1287 -     armoryDBDir     : DEFAULT
2017-08-01 03:03:52 (INFO) -- ArmoryUtils.py:1287 -     armorydb_port   : 55555
...
2017-08-01 03:03:53 (INFO) -- ArmoryQt.py:1837 - startBitcoindIfNecessary
2017-08-01 03:03:53 (INFO) -- ArmoryQt.py:5729 - --> completeBlockchainProcessingInitialization
2017-08-01 03:03:53 (INFO) -- ArmoryQt.py:1778 - --- - - - - - -STARTING DB---------------
2017-08-01 03:03:53 (INFO) -- ArmoryQt.py:1787 - --- localDBPort:
2017-08-01 03:03:53 (INFO) -- ArmoryQt.py:1788 - 9001
2017-08-01 03:03:53 (INFO) -- ArmoryQt.py:1791 - --> HERE
```

is there another default somewhere? even if i change https://github.com/goatpig/BitcoinArmory/blob/master/armoryengine/ArmoryUtils.py#L89 i'm still getting 9001 as the local port

**Comment by goatpig** [comment]
This is a bit odd.

It returns 9001 because 

1) It fails to find any listening socket on your custom port
2) It finds a process on 9001 (fallback if if fails with the custom port).

Are you spawning the DB manually or letting the client do it for you?

**Comment by joernroeder** [comment]
i didnt spawn it. i was hoping it would pick up my 55555 from the .conf files as i did it manually

**Comment by joernroeder** [comment]
but shouldnt it fallback to the (changed) `ARMORYDB_DEFAULT_PORT`?

**Comment by goatpig** [comment]
Ok now I understand what's going on. This is the code that tests for the port:

https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BlockDataManagerConfig.cpp#L667

This will first test the custom port (if there is one, otherwise it's the default port), then the default port, then check for the randomized port in the cookie file.

Your issue is this:

When you let Armory randomize the port, it finds a process listening on the default and believes this is the DB, which it shouldn't.

When you set a custom port, the DB is still spawned with --cookie, therefor it ignores the custom port (--cookie overrules custom ports, since it's explicitly meant to let the client overwrite the DB settings when spawning it).

The fix is to add a challenge on top of the connection to make sure it is talking an actual Armory DB and not just any process.

Your short term fix is to either manually spawn the DB, or figure out what's listening to 9001 and shutting it down.

**Comment by joernroeder** [comment]
You're totally right. When I nmap 127.0.0.1 I see another process! Doing some kind of handshake or health check should be the solution. 

Thanks again!

**Comment by goatpig** [comment]
I'll add the handshake in testing sometimes tomorrow (getting late and other items on my list). You'll have to build that branch or wait for the RC for 0.96.2

**Comment by joernroeder** [comment]
sounds great! Let me know if i can help you out or test something! I've created a little script to start the db and armory with the commandline args which i use in the meantime.

**Comment by jameshilliard** [comment]
I've seen this error when trying to generate receive addresses on 0.96.1, not sure if it's related.
```
BDM is ready!
-ERROR - 15:43:09: (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unexpected fcgi header version
-ERROR - 15:43:09: (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unexpected fcgi header version
(ERROR) Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/QtExecuteSignal.py", line 31, in methodSlot
    _callable(*args)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py", line 4950, in handleCppNotification
    self.changeWltFilter()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py", line 822, in changeWltFilter
    TheBDM.bdv().updateWalletsLedgerFilter(self.wltIDList)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/CppBlockUtils.py", line 2756, in updateWalletsLedgerFilter
    return _CppBlockUtils.BlockDataViewer_updateWalletsLedgerFilter(self, wltIdVec)
RuntimeError: can't connect socket

Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/QtExecuteSignal.py", line 31, in methodSlot
    _callable(*args)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py", line 4950, in handleCppNotification
    self.changeWltFilter()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py", line 822, in changeWltFilter
    TheBDM.bdv().updateWalletsLedgerFilter(self.wltIDList)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/CppBlockUtils.py", line 2756, in updateWalletsLedgerFilter
    return _CppBlockUtils.BlockDataViewer_updateWalletsLedgerFilter(self, wltIdVec)
RuntimeError: can't connect socket
```

**Comment by joernroeder** [comment]
just in case someone is running into the same problem. I'm using the following script to boot up my Armory instance:

```bash
# /Applications/start-armory.sh

echo "- starting ArmoryDB"
/Applications/Armory.app/Contents/MacOS/py/usr/local/bin/ArmoryDB --fcgi-port=55555 &

echo "- waiting for ArmoryDB to start"
sleep 20

echo "- starting Armory"
/Applications/Armory.app/Contents/MacOS/Armory --armorydb-port=55555
```

@goatpig do you have schedule when a fix for this issue will land in an upcoming release?
