### ISSUE TITLE
"Export Key Lists" (Step 4: Backup Wallet) does not work

### ISSUE THREAD

**Issue by nimbosa** [goatpig/BitcoinArmory#281]
i was able to build the latest testing branch as of **2017-08-02 17:32:08** (26cd6401245ce6e28c47234f8ec795290d0c103a)

it installs and starts successfully, it recovers old backups and can create new wallets but could not **"Export Key Lists"** (Step 4: Backup Wallet), instead of expected behaviour, it does nothing, other backup options are working, though:

```
(ERROR) Traceback (most recent call last):
  File "~/BitcoinArmory/qtdialogs.py", line 12353, in verifyUserInput
    rawBin, err = readSixteenEasyBytes(rawEntry.replace(' ', ''))
  File "~/BitcoinArmory/armoryengine/ArmoryUtils.py", line 2256, in readSixteenEasyBytes
    raise ValueError('Must supply 18-byte input')
ValueError: Must supply 18-byte input

Traceback (most recent call last):
  File "~/BitcoinArmory/qtdialogs.py", line 12353, in verifyUserInput
    rawBin, err = readSixteenEasyBytes(rawEntry.replace(' ', ''))
  File "~/BitcoinArmory/armoryengine/ArmoryUtils.py", line 2256, in readSixteenEasyBytes
    raise ValueError('Must supply 18-byte input')
ValueError: Must supply 18-byte input
-ERROR - : (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unknown fcgi header request byte
-ERROR - : (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unknown fcgi header request byte
-ERROR - : (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unknown fcgi header request byte
-ERROR - : (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unknown fcgi header request byte
-ERROR - : (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unknown fcgi header request byte

(ERROR) Traceback (most recent call last):
  File "~/BitcoinArmory/ui/WalletFrames.py", line 1136, in clickedDoIt
    DlgShowKeyList(self.wlt, self.parent(), self.main).exec_()
  File "~/BitcoinArmory/qtdialogs.py", line 4948, in __init__
    self.rewriteList()
  File "~/BitcoinArmory/qtdialogs.py", line 5010, in rewriteList
    addrIndex = self.wlt.cppWallet.getAssetIndexForAddr(addr.getAddr160())
AttributeError: 'NoneType' object has no attribute 'getAssetIndexForAddr'

Traceback (most recent call last):
  File "~/BitcoinArmory/ui/WalletFrames.py", line 1136, in clickedDoIt
    DlgShowKeyList(self.wlt, self.parent(), self.main).exec_()
  File "~/BitcoinArmory/qtdialogs.py", line 4948, in __init__
    self.rewriteList()
  File "~/BitcoinArmory/qtdialogs.py", line 5010, in rewriteList
    addrIndex = self.wlt.cppWallet.getAssetIndexForAddr(addr.getAddr160())
AttributeError: 'NoneType' object has no attribute 'getAssetIndexForAddr'
-ERROR - : (StringSockets.cpp:351) FcgiSocket::writeAndRead FcgiError: unknown fcgi header request byte
(ERROR) Traceback (most recent call last):
  File "~/BitcoinArmory/ui/WalletFrames.py", line 1136, in clickedDoIt
    DlgShowKeyList(self.wlt, self.parent(), self.main).exec_()
  File "~/BitcoinArmory/qtdialogs.py", line 4948, in __init__
    self.rewriteList()
  File "~/BitcoinArmory/qtdialogs.py", line 5010, in rewriteList
    addrIndex = self.wlt.cppWallet.getAssetIndexForAddr(addr.getAddr160())
AttributeError: 'NoneType' object has no attribute 'getAssetIndexForAddr'
```

**Comment by goatpig** [comment]
You're trying to do this in offline mode?

**Comment by goatpig** [comment]
I cannot reproduce this issue on testing, please try to narrow down the issue.
