### ISSUE TITLE
Unable to send bitcoins from Armory

### ISSUE THREAD

**Issue by r-vinodh** [goatpig/BitcoinArmory#343]
I am unable to send bitcoins from Armory due to a timeout issue. I am sending the transaction with a much higher fees but its still failing. Please find the error log attached. 
[armorylog_20171023_2025.txt](https://github.com/goatpig/BitcoinArmory/files/1409420/armorylog_20171023_2025.txt)

**Comment by mtlynch** [comment]
I'm seeing the same thing ever since upgrading from 0.96.0 -> 0.96.3.

It warns that my fee is too low, but when I click, "Yes" nothing happens. Even if I change it to 200 sat/byte, nothing happens when I hit "Send."

This is on Win10 x64 / Armory 0.96.3 / Bitcoin Core v0.15.0.1.

**Comment by goatpig** [comment]
vindo84: update

mtlynch: wrong log, need armorylog.txt

**Comment by mtlynch** [comment]
Ah, sorry. Here you go:

```
2017-10-24 17:40:12 (INFO) -- TxFrames.pyc:727 - Change address behavior: NewAddr
2017-10-24 17:40:12 (ERROR) -- Traceback (most recent call last):
  File "ui\TxFrames.pyc", line 848, in createTxAndBroadcast
  File "ui\TxFrames.pyc", line 802, in validateInputsGetUSTX
  File "armoryengine\Transaction.pyc", line 2287, in createFromTxOutSelection
  File "armoryengine\Transaction.pyc", line 2196, in createFromPyTx
  File "CppBlockUtils.pyc", line 2994, in getTxByHash
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x000000000651D210> >

2017-10-24 17:40:27 (INFO) -- TxFrames.pyc:727 - Change address behavior: NewAddr
2017-10-24 17:40:27 (ERROR) -- Traceback (most recent call last):
  File "ui\TxFrames.pyc", line 848, in createTxAndBroadcast
  File "ui\TxFrames.pyc", line 802, in validateInputsGetUSTX
  File "armoryengine\Transaction.pyc", line 2287, in createFromTxOutSelection
  File "armoryengine\Transaction.pyc", line 2196, in createFromPyTx
  File "CppBlockUtils.pyc", line 2994, in getTxByHash
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x000000000651D5A0> >

2017-10-24 17:40:51 (INFO) -- ArmoryQt.py:3672 - Log saved to //DISKSTATION/Data/tmp/armorylog_20171024_1740.txt
2017-10-24 17:42:39 (WARNING) -- ArmoryQt.py:4108 - Called updateSyncProgress while not sync'ing
2017-10-24 17:43:07 (WARNING) -- ArmoryQt.py:4108 - Called updateSyncProgress while not sync'ing
2017-10-24 17:43:12 (INFO) -- ArmoryQt.py:4944 - New Block! : 491548
2017-10-24 17:43:12 (INFO) -- ArmoryQt.py:4952 - Current block number: 491548
```

**Comment by mtlynch** [comment]
>mtlynch: 0.96.3 is not compatible with 0.15.0.1, use 0.96.4 RC1 or downgrade your node.

Gotcha, thanks for the quick response!

**Comment by mtlynch** [comment]
On 0.96.4 RC1, I'm seeing this:

```
2017-10-24 18:36:56 (ERROR) -- Traceback (most recent call last):
  File "ArmoryQt.py", line 3452, in clickSendBitcoins
  File "qtdialogs.pyc", line 4593, in __init__
  File "ui\TxFrames.pyc", line 150, in __init__
  File "ui\WalletFrames.pyc", line 232, in __init__
  File "ui\WalletFrames.pyc", line 345, in updateOnWalletChange
  File "ui\TxFrames.pyc", line 347, in setWallet
  File "ui\TxFrames.pyc", line 396, in setupCoinSelectionInstance
  File "CppBlockUtils.pyc", line 4116, in getCoinSelectionInstance
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x0000000006A98ED0> >
```
https://gist.github.com/mtlynch/57143932dc4adc7b87575b5f0c0733b8

**Comment by goatpig** [comment]
Do a rebuild & rescan

**Comment by heywheelie** [comment]
I am having the same problem tryin
[armorylog_20171025_1222.txt](https://github.com/goatpig/BitcoinArmory/files/1413129/armorylog_20171025_1222.txt)
g to send bitcoin.  Using armory 0.96.0 and bitcoin core 0.14.2

**Comment by vindo84** [comment]
@goatpig I am still facing this issue and its been happening for more than a month now.
I am using the latest armory version 0.96.0.
Please find the log file attached.
Please help me send bitcoins out of armory.
[armorylog_20171024_2029.txt](https://github.com/goatpig/BitcoinArmory/files/1413170/armorylog_20171024_2029.txt)

**Comment by heywheelie** [comment]
Armory is now showing my failed send transfers as unconfirmed and no longer spendable.  Does that mean I have lost them?  Is there any way to get them back?

**Comment by goatpig** [comment]
0.96 is from April, use the latest version please.

> Does that mean I have lost them? Is there any way to get them back?

You seem to have little understanding of how transactions take place on the Bitcoin network. I am referring you to the Armory forum where you can get basic troubleshooting. I assume posters on the github issue page have fundamental Bitcoin knowledge.

https://bitcointalk.org/index.php?board=97.0

**Comment by mtlynch** [comment]
Working now, thanks for your help. Do you accept BTC donations?

**Comment by goatpig** [comment]
No

**Comment by mtlynch** [comment]
Cool, just send me your dogecoin address then.

(Just kidding, thanks for the work you do)

**Comment by heywheelie** [comment]
thank you

**Comment by vindo84** [comment]
@goatpig  sorry, its still not working for me. I tried upgrading armory to both 0.96.2 & 0.96.3 but both these version failed to come online. They are continuously in offline mode and not showing up my balances. Please find attached the error log, thanks for the help!
[armorylog_20171025_1846.txt](https://github.com/goatpig/BitcoinArmory/files/1416718/armorylog_20171025_1846.txt)

**Comment by goatpig** [comment]
Ask on the forums, you are having issues with the basic setup.

**Comment by gregspencewu** [comment]
I am having the same issue. 

Couldn't get Armory online, so reverted to previous version of the Core. Armory now online but can't send Bitcoins. 

[armorylog_20171028_1421.txt](https://github.com/goatpig/BitcoinArmory/files/1424623/armorylog_20171028_1421.txt)

**Comment by jeremyhannon** [comment]
> mtlynch: 0.96.3 is not compatible with 0.15.0.1, use 0.96.4 RC1 or downgrade your node.

This was invaluable. 
core 0.15.0.1 + armory 0.96.3 - didn't work
core 0.15.0.1 + armory 0.96.4 RC1 - didn't work
core 0.14.2 + armory 0.96.3 - finally worked after rebuilding the entire blockchain

FYI I had been seeing the [`non-mandatory-script-verify-flag (Signature must use SIGHASH_FORKID)`](https://bitcointalk.org/index.php?topic=2070058.msg21208650#msg21208650) error when it failed.

**Comment by TAiS46** [comment]
Will this be fixed soon? rebuilding the blockchain takes really long ...
