### ISSUE TITLE
picks wrong signer for segwit tx - UnserializeError

### ISSUE THREAD

**Issue by tjol** [goatpig/BitcoinArmory#385]
Armory currently recommends using segwit (change) addresses, and then can't spend its own coins.
This error appears in the output both with 0.96.3 and current HEAD:

```
Traceback (most recent call last):
  File "/home/tjol/Software/BitcoinArmory/ui/TxFrames.py", line 871, in createTxAndBroadcast
    finalTx = ustxSigned.getSignedPyTx(signer=self.signerType)
  File "/home/tjol/Software/BitcoinArmory/armoryengine/Transaction.py", line 2633, in getSignedPyTx
    if not self.verifySigsAllInputs(signer):
  File "/home/tjol/Software/BitcoinArmory/armoryengine/Transaction.py", line 2549, in verifySigsAllInputs
    pytx = self.getSignedPyTx(doVerifySigs=False)
  File "/home/tjol/Software/BitcoinArmory/armoryengine/Transaction.py", line 2661, in getSignedPyTx
    pytxWit.unserialize(witData)
  File "/home/tjol/Software/BitcoinArmory/armoryengine/Transaction.py", line 672, in unserialize
    if txWitnessData.getRemainingSize() < stackItemSize: raise UnserializeError
armoryengine.ArmoryUtils.UnserializeError
```

It turns out that manually switching to the C++ signer solves this problem: https://bitcointalk.org/index.php?topic=2133694.msg21364768

Armory should, by default, especially when not in Expert mode, pick defaults that, above all, *work*.

As it stands, Armory in Advanced mode allowed me to place my bitcoins somewhere I couldn't spend them AT ALL without switching to Expert mode. (which gave me quite a fright before I found, and managed to understand, that forum thread)

[Obviously this is something you know about, I just want to put forward the notion that it's a serious bug, not an adorable quirk]

**Comment by goatpig** [comment]
This has been fixed in testing a couple months ago
