### ISSUE TITLE
Unable to sweep legacy private key into P2SH-P2WPKH Segwit offline watch only wallet.

### ISSUE THREAD

**Issue by Reysalmon** [goatpig/BitcoinArmory#425]
When Armory is set to use P2SH-P2WPKH It's unable to sweep a legacy paper wallet.

Attempting to sweep the paper wallet opens a dialog window showing the public address and amount held within. Trying to continue does nothing, no transaction is created or broadcasted.

Cancelling and checking the address book afterwards shows an unused legacy address was generated, but not used.

Looks like it may be an issue in the way  the sweep function requests an address and the preferred receiving address type.

**Comment by droark** [comment]
Thanks for the report. Can you please post your logs?

**Comment by Reysalmon** [comment]
Thanks for the reply. I ran into this problem a few weeks back, and only had some time to make a post now based on memory. I don't believe it showed an amount, I was mixing that up with Electrums sweep function. 

The original logs and paper wallet are gone/inaccessible, solution at the time was to use electrum to sweep directly into Armory receive address.

Trying to re-create the issue has me believing it may be related to Armory not supporting WIF compressed keys. Using Bitaddress to generate a wallet for testing, importing/sweeping the non-compressed key gets a silent error (no ui notification) likely in regards to no spendable inputs being found.

2018-01-01 22:46:51 (INFO) -- ArmoryQt.py:3045 - finishSweepScan
2018-01-01 22:46:51 (INFO) -- ArmoryQt.py:2924 - createSweepAddrTx
2018-01-01 22:46:51 (ERROR) -- Traceback (most recent call last):
  File "qtdialogs.pyc", line 2605, in okayClicked
  File "qtdialogs.pyc", line 2738, in processUserString
  File "armoryengine\PyBtcWallet.pyc", line 59, in inner
  File "armoryengine\PyBtcWallet.pyc", line 3161, in sweepAddressList
  File "armoryengine\PyBtcWallet.pyc", line 59, in inner
  File "armoryengine\PyBtcWallet.pyc", line 3140, in doAfterScan
  File "armoryengine\PyBtcWallet.pyc", line 59, in inner
  File "armoryengine\PyBtcWallet.pyc", line 3148, in sweepAfterRescan
  File "ArmoryQt.py", line 3052, in finishSweepScan
  File "ArmoryQt.py", line 2929, in createSweepAddrTx
  File "armoryengine\Transaction.pyc", line 3285, in getUnspentTxOutsForAddr160List
  File "CppBlockUtils.pyc", line 3045, in getUtxosForAddrVec
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x00000000090BAF00> >

At the same time a new address is generated in the address book but it starts with a 1 despite segwit preferred settings.

Attempting to import the compressed key gives an invalid private key error. 

I'm leaning towards user error on my part in trying to sweep a non-compressed private key from a compressed format address which resulted in a silent error due to no inputs being found.

**Comment by droark** [comment]
@goatpig - Any thoughts on this? I don't think Armory supports WIF compressed keys but maybe there are some recent changes I've forgotten about?

**Comment by goatpig** [comment]
@droark It does not, will have it for the new wallets in 0.97
