### ISSUE TITLE
Armory 0.96.4: "Preview Transaction" no longer works

### ISSUE THREAD

**Issue by Saicere** [goatpig/BitcoinArmory#519]
When creating a transaction on a watch-only wallet from a P2PKH output, Preview Transaction no longer works in Armory 0.96.4. The following error is printed in the logs:

(ERROR) -- Traceback (most recent call last):
  File "ui\TxFrames.pyc", line 1429, in previewTx
  File "qtdialogs.pyc", line 5423, in __init__
  File "armoryengine\ArmoryUtils.pyc", line 2009, in hex_to_binary
  File "encodings\hex_codec.pyc", line 42, in hex_decode
TypeError: Non-hexadecimal digit found

Presumably, since the TXID of an unsigned transaction spending non-segwit inputs cannot be determined, it's passing some invalid value here. This was working in 0.96.3.

**Comment by goatpig** [comment]
Thanks for the bug report, will look into it.
