### ISSUE TITLE
Send button unresponsive 

### ISSUE THREAD

**Issue by dffffffff** [goatpig/BitcoinArmory#539]
macOS 10.14.1 Armory 0.94.4-beta-fee1f91a31

Send button is unresponsive when the client is fully operational.
During syncing it works as intended by letting user know they have to wait to send.

Tested in advanced and in standard user mode

**Comment by goatpig** [comment]
Post your logs please.

**Comment by dffffffff** [comment]
(ERROR) Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py", line 3452, in clickSendBitcoins
    DlgSendBitcoins(self.getSelectedWallet(), self, self).exec_()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/qtdialogs.py", line 4593, in __init__
    spendFromLockboxID=spendFromLockboxID)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/TxFrames.py", line 150, in __init__
    RBFcallback=RBFcallback)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/WalletFrames.py", line 232, in __init__
    self.updateOnWalletChange()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/WalletFrames.py", line 347, in updateOnWalletChange
    self.selectWltCallback(wlt)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/TxFrames.py", line 346, in setWallet
    self.setupCoinSelectionInstance()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/TxFrames.py", line 395, in setupCoinSelectionInstance
    self.coinSelection = self.wlt.cppWallet.getCoinSelectionInstance()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/CppBlockUtils.py", line 3795, in getCoinSelectionInstance
    return _CppBlockUtils.WalletContainer_getCoinSelectionInstance(self)
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x110471b70> >

Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py", line 3452, in clickSendBitcoins
    DlgSendBitcoins(self.getSelectedWallet(), self, self).exec_()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/qtdialogs.py", line 4593, in __init__
    spendFromLockboxID=spendFromLockboxID)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/TxFrames.py", line 150, in __init__
    RBFcallback=RBFcallback)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/WalletFrames.py", line 232, in __init__
    self.updateOnWalletChange()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/WalletFrames.py", line 347, in updateOnWalletChange
    self.selectWltCallback(wlt)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/TxFrames.py", line 346, in setWallet
    self.setupCoinSelectionInstance()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ui/TxFrames.py", line 395, in setupCoinSelectionInstance
    self.coinSelection = self.wlt.cppWallet.getCoinSelectionInstance()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/CppBlockUtils.py", line 3795, in getCoinSelectionInstance
    return _CppBlockUtils.WalletContainer_getCoinSelectionInstance(self)
<class 'CppBlockUtils.DbErrorMsg'>: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x110471b70> >

**Comment by goatpig** [comment]
This is a setup issue on your end, please refer to the community forums with your full logs for further assistance:

https://bitcointalk.org/index.php?board=97.0
