### ISSUE TITLE
Crash after fresh install on Windows 8.1

### ISSUE THREAD

**Issue by kickbehindseabass1234** [goatpig/BitcoinArmory#9]
Install seemed successful. On first run of newly installed program got a crash telling me to look at ArmoryQt.exe.log for details (contents of that file pasted below). If it's relevant, the computer I tried it on has an internet connection and runs Bitcoin Core (probably v0.11.2) with testnet blockchain. (Feel free to ignore this issue if it's not helpful or I've done something stupid, I'm just posting in case it's helpful, I've no intention of using Armory on this machine other than to maybe test a bit.)

(ERROR) ArmoryQt.py:2857 - ***WARNING: Wallet could not be loaded: C:\Users\goat\AppData\Roaming\Armory\armory_34N5W7Ts5_.WatchOnly.wallet (skipping)
Traceback (most recent call last):
  File "ArmoryQt.py", line 2823, in loadWalletsAndSettings
  File "armoryengine\Timer.pyc", line 99, in inner
  File "armoryengine\PyBtcWallet.pyc", line 2086, in readWalletFile
  File "armoryengine\PyBtcWallet.pyc", line 1973, in unpackHeader
  File "armoryengine\PyBtcWallet.pyc", line 1905, in unpackWalletFlags
isMSWallet: Cannot Open MS Wallets
(ERROR) ArmoryQt.py:2857 - ***WARNING: Wallet could not be loaded: C:\Users\goat\AppData\Roaming\Armory\armory_FGdyYeKZ_.WatchOnly.wallet (skipping)
Traceback (most recent call last):
  File "ArmoryQt.py", line 2823, in loadWalletsAndSettings
  File "armoryengine\Timer.pyc", line 99, in inner
  File "armoryengine\PyBtcWallet.pyc", line 2086, in readWalletFile
  File "armoryengine\PyBtcWallet.pyc", line 1973, in unpackHeader
  File "armoryengine\PyBtcWallet.pyc", line 1905, in unpackWalletFlags
isMSWallet: Cannot Open MS Wallets
(ERROR) ArmoryQt.py:2857 - ***WARNING: Wallet could not be loaded: C:\Users\goat\AppData\Roaming\Armory\armory_34N5W7Ts5_.WatchOnly.wallet (skipping)
Traceback (most recent call last):
  File "ArmoryQt.py", line 2823, in loadWalletsAndSettings
  File "armoryengine\Timer.pyc", line 99, in inner
  File "armoryengine\PyBtcWallet.pyc", line 2086, in readWalletFile
  File "armoryengine\PyBtcWallet.pyc", line 1973, in unpackHeader
  File "armoryengine\PyBtcWallet.pyc", line 1905, in unpackWalletFlags
isMSWallet: Cannot Open MS Wallets
(ERROR) ArmoryQt.py:2857 - ***WARNING: Wallet could not be loaded: C:\Users\goat\AppData\Roaming\Armory\armory_FGdyYeKZ_.WatchOnly.wallet (skipping)
Traceback (most recent call last):
  File "ArmoryQt.py", line 2823, in loadWalletsAndSettings
  File "armoryengine\Timer.pyc", line 99, in inner
  File "armoryengine\PyBtcWallet.pyc", line 2086, in readWalletFile
  File "armoryengine\PyBtcWallet.pyc", line 1973, in unpackHeader
  File "armoryengine\PyBtcWallet.pyc", line 1905, in unpackWalletFlags
isMSWallet: Cannot Open MS Wallets
(ERROR) Traceback (most recent call last):
  File "ArmoryQt.py", line 7135, in <module>
  File "ArmoryQt.py", line 258, in __init__
  File "ArmoryQt.py", line 2475, in startBitcoindIfNecessary
  File "ArmoryQt.py", line 2428, in findTorrentFileForSDM
AttributeError: 'ArmoryMainWindow' object has no attribute 'announceFetcher'

Traceback (most recent call last):
  File "ArmoryQt.py", line 7135, in <module>
  File "ArmoryQt.py", line 258, in __init__
  File "ArmoryQt.py", line 2475, in startBitcoindIfNecessary
  File "ArmoryQt.py", line 2428, in findTorrentFileForSDM
AttributeError: 'ArmoryMainWindow' object has no attribute 'announceFetcher'

**Comment by goatpig** [comment]
You have to skip the torrent fetch part. In essence, the underlying Bitcoin instance has no block data, or Armory has not been properly pointed at that data.

If you have the blockchain data, point Armory towards that using the --satoshi-datadir=*path* command line argument, or start Armory in offline mode and set the path in Files -> Settings, within the first section.

If you do not have any blockchain data, or are missing most of it, start BitcoinQt manually and let it sync.

Seeing that you are running this on testnet, you would need to start BitcoinQt with the -testnet command line argument.

Once you are past this point Armory should start fine. For your information, I will be deleting the torrent code in the next testing build.
